spring:
  profiles:
    active: dev

---
spring:
  application:
    name: file_processor
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/requests_logs?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:requests_logs_test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create